#!/bin/bash

AWS_DEFAULT_REGION="eu-west-1"
BRANCH=$(git rev-parse --abbrev-ref HEAD)

BUILDPARAMS=""
DOCKERNAME="616233846889.dkr.ecr.eu-west-1.amazonaws.com/flowbase:${BRANCH}"

eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) \
    2>/dev/null

if docker pull ${DOCKERNAME} 2>/dev/null; then
    BUILDPARAMS="$BUILDPARAMS --cache-from ${DOCKERNAME}"
fi

if DOCKER_BUILDKIT=1 docker build \
    ${BUILDPARAMS} \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --build-arg BRANCH=$BRANCH \
    --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    --build-arg CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN \
    --build-arg BACKEND_AWS_REGION=$AWS_DEFAULT_REGION \
    -t "$DOCKERNAME" . 
then
    echo docker built sucessfully
else
    echo ERROR: cant build docker
    exit 1
fi

docker push "$DOCKERNAME"
