#!/bin/bash

AWS_DEFAULT_REGION="eu-west-1"

REPO_BRANCH=$(git rev-parse --abbrev-ref HEAD)
BRANCH="${BRANCH:-$REPO_BRANCH}"
SHA="$(git rev-parse HEAD)"
TAG=${BRANCH}_${1/.Dockerfile/}

BUILDPARAMS=""
DOCKERNAME="616233846889.dkr.ecr.eu-west-1.amazonaws.com/flowbase:${TAG}"

eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) \
    2>/dev/null

if docker pull ${DOCKERNAME} 2>/dev/null; then
    BUILDPARAMS="$BUILDPARAMS --cache-from ${DOCKERNAME}"
fi

if DOCKER_BUILDKIT=1 docker build \
    ${BUILDPARAMS} \
    --shm-size 2048M \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --build-arg BRANCH=$BRANCH \
    --build-arg SHA=$SHA \
    --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    --build-arg CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN \
    --build-arg CLOUDFLARE_ZONE=$CLOUDFLARE_ZONE \
    --build-arg BACKEND_AWS_REGION=$AWS_DEFAULT_REGION \
    --build-arg YANDEX_BOT_EMAIL=$YANDEX_BOT_EMAIL \
    --build-arg YANDEX_BOT_TOKEN=$YANDEX_BOT_TOKEN \
    --build-arg GOOGLE_PAGESPEED_KEY=$GOOGLE_PAGESPEED_KEY \
    --build-arg TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN \
    -f $1 \
    -t "$DOCKERNAME" . 
then
    echo docker built sucessfully
else
    echo ERROR: cant build docker
    exit 1
fi

docker push "$DOCKERNAME"
