#!/bin/bash

CONTAINER_NAME="flowbase"
AWS_DEFAULT_REGION="eu-west-1"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

BUILDPARAMS=""
RUNPARAMS=""
DOCKERNAME="616233846889.dkr.ecr.eu-west-1.amazonaws.com/flowbase:${BRANCH_NAME}"

if [ "$1" != "local" ]; then
    eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 2>/dev/null

    if docker pull ${DOCKERNAME} 2>/dev/null; then
        BUILDPARAMS="$BUILDPARAMS --cache-from ${DOCKERNAME}"
    fi
fi

if docker build ${BUILDPARAMS} -t "$DOCKERNAME" .
then
    echo docker built sucessfully
else
    echo ERROR: cant build docker
    exit 1
fi

if [ "$1" != "local" ]; then
    docker push "$DOCKERNAME"
fi

docker rm -f $CONTAINER_NAME 2>/dev/null
docker run -t --rm --name $CONTAINER_NAME \
    ${RUNPARAMS} \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -e CLOUDFLARE_API_TOKEN \
    -e SLACK_BOT_TOKEN \
    -e GOOGLE_ANALYTICS \
    -e BRANCH_NAME=$BRANCH_NAME \
    -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
    "$DOCKERNAME" bash -c "$2"
